name: Deploy to Server
on:
  push:
    branches: [ main ]
jobs:
  create-deployment-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile css and js
      run: |
        npm install
        npm run build
