name: Main YML
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
run-name: Running Main YML
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh cicd
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: nirojprasaincom
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 1980
          script: 'cd /home2/nirojprasaincom/anil/college && ./deploy.sh'


