
name: Deploy
on:
  push:
    branches: [ main ]

run-name: Deploy to Server
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |


            cd /home/meriaama/skps.edu.np
            composer install --optimize-autoloader --no-dev
            php artisan config:cache
            php artisan event:cache
            php artisan route:cache
            php artisan view:cache
