name: Main YML
on:
  push:
    branches: [main]
run-name: Running Main YML
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh cicd
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: rgbitsol
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/rgbitsol/test/cicd
            php artisan config:cache
            php artisan event:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate
