name: Test yml
on:
  push:
    branches: [main]

run-name: Test yml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh cicd
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: rgbitsol
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |


            cd /home/rgbitsol/test/cicd
            php artisan config:cache
            php artisan event:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate
